#heading(level: 1, numbering: none)[Перечень сокращений и условных обозначений]

#table(
  columns: (auto, 1fr),
  align: (left, left),
  stroke: none,
  inset: (x: 0pt, y: 2pt),
  [*ACID*], [Atomicity, Consistency, Isolation, Durability — атомарность, согласованность, изолированность, долговечность (требования к транзакционной системе)],
  [*API*], [Application Programming Interface — интерфейс программирования приложений],
  [*ADR*], [Architecture Decision Record — запись об архитектурном решении],
  [*BUC*], [Business Use Case — бизнес-прецедент],
  [*CRUD*], [Create, Read, Update, Delete — создание, чтение, обновление, удаление],
  [*CSS*], [Cascading Style Sheets — каскадные таблицы стилей],
  [*CSRF*], [Cross-Site Request Forgery — межсайтовая подделка запроса],
  [*CORS*], [Cross-Origin Resource Sharing — совместное использование ресурсов между разными источниками],
  [*DDD*], [Domain-Driven Design — предметно-ориентированное проектирование],
  [*DDL*], [Data Definition Language — язык описания данных],
  [*DOM*], [Document Object Model — объектная модель документа],
  [*DTO*], [Data Transfer Object — объект передачи данных],
  [*ER*], [Entity-Relationship — сущность-связь],
  [*GoF*], [Gang of Four — «банда четырёх», авторы классических паттернов проектирования],
  [*HTML*], [HyperText Markup Language — язык разметки гипертекста],
  [*HTTP*], [HyperText Transfer Protocol — протокол передачи гипертекста],
  [*IDEF0*], [Integration Definition for Function Modeling — методология функционального моделирования],
  [*JPA*], [Java Persistence API — интерфейс сохранения объектов Java],
  [*JRE*], [Java Runtime Environment — среда выполнения Java],
  [*JSON*], [JavaScript Object Notation — текстовый формат обмена данными],
  [*JWT*], [JSON Web Token — токен доступа в формате JSON],
  [*KLOC*], [Kilo Lines of Code — тысяча строк исходного кода],
  [*LTS*], [Long Term Support — долгосрочная поддержка программного обеспечения],
  [*MIME*], [Multipurpose Internet Mail Extensions — многоцелевые расширения интернет-почты (стандарт описания типов файлов)],
  [*OAuth*], [Open Authorization — открытый протокол авторизации],
  [*OIDC*], [OpenID Connect — протокол идентификации поверх OAuth 2.0],
  [*ORM*], [Object-Relational Mapping — объектно-реляционное отображение],
  [*OWASP*], [Open Worldwide Application Security Project — открытый проект обеспечения безопасности приложений],
  [*PCMEF*], [Presentation-Control-Mediator-Entity-Foundation — паттерн многослойной архитектуры],
  [*REST*], [Representational State Transfer — архитектурный стиль взаимодействия компонентов распределённого приложения],
  [*RPS*], [Requests Per Second — запросов в секунду],
  [*SDK*], [Software Development Kit — комплект средств разработки],
  [*SLOC*], [Source Lines of Code — строки исходного кода],
  [*SPA*], [Single Page Application — одностраничное веб-приложение],
  [*SPOF*], [Single Point of Failure — единая точка отказа],
  [*SQL*], [Structured Query Language — язык структурированных запросов],
  [*SSE*], [Server-Sent Events — события, отправляемые сервером],
  [*SSO*], [Single Sign-On — единая точка входа],
  [*SWOT*], [Strengths, Weaknesses, Opportunities, Threats — анализ сильных и слабых сторон, возможностей и угроз],
  [*TTL*], [Time To Live — время жизни записи в кэше],
  [*UC*], [Use Case — прецедент использования],
  [*UI*], [User Interface — пользовательский интерфейс],
  [*URL*], [Uniform Resource Locator — единый указатель ресурса],
  [*WBS*], [Work Breakdown Structure — иерархическая структура работ],
  [*XSS*], [Cross-Site Scripting — межсайтовый скриптинг],
  [*XML*], [eXtensible Markup Language — расширяемый язык разметки],
  [*3НФ*], [Третья нормальная форма — уровень нормализации реляционной базы данных],
  [*ОЗУ*], [Оперативное запоминающее устройство],
  [*ROI*], [Return on Investment — возврат инвестиций],
)
